import type { CoverStyle } from '../services/coverSuggestion';
/**
 * Structured distillation of a style guide's mechanical rules.
 *
 * Why this exists: relying on the LLM to "read the PDF and follow it"
 * is unreliable for the deterministic parts of academic style — first-
 * vs-subsequent footnote format, ibid sequences, block-quote
 * thresholds, quote-mark conventions. The user explicitly raised this
 * concern: that Gemini might process the guide as soft context and
 * miss hard rules. The manifest captures those rules as structured
 * data that two consumers use:
 *
 *   1. The orchestrator's prompt — the manifest is rendered as a
 *      "hard rules" block (templates and thresholds), giving the LLM
 *      stronger compliance pressure than free-form guide text.
 *   2. The post-processor (`IStyleFormatter`) — runs deterministic
 *      passes after generation: rewrite second-mention footnotes to
 *      the abbreviated form, collapse consecutive same-source
 *      footnotes to ibid, normalize quote marks, enforce block-quote
 *      thresholds. Anything the LLM gets wrong here is fixable by
 *      pure text manipulation.
 *
 * The manifest does NOT replace the raw style guide text. Both are
 * injected into prompts: the structured manifest as hard rules, the
 * raw text as fallback context for cases the manifest doesn't cover
 * (idiomatic phrasing, abbreviation tables, etc.).
 *
 * Storage: lives on `UserStyleGuide.manifest` (added to that entity
 * in Phase 1D). One manifest per guide; re-extracted when the user
 * uploads a new guide version. Kept inline because the manifest is
 * small (a few KB) and always read together with the guide pointer.
 */
export interface StyleGuideManifest {
    /**
     * How the manifest was produced.
     *   'extracted'   — generated by `IStyleGuideManifestExtractor`
     *                   from the uploaded guide.
     *   'user-edited' — student corrected the extracted manifest in
     *                   the verification UI.
     *   'system-default' — no guide uploaded; we apply a sensible TMS
     *                   default so generation can still run with
     *                   reasonable rules.
     */
    provenance: 'extracted' | 'user-edited' | 'system-default';

    /** ISO timestamp the extractor ran (or the user last edited). */
    extractedAt: Date;

    /** Identifier of the model that produced the extraction. Empty for system defaults. */
    extractorModelId: string;

    /** Citation style label as the guide names it ("Turabian 9", "TMS 2024-25", "SBL Handbook"). */
    citationStyleLabel: string;

    /** Footnote rules — the most error-prone mechanical part of academic style. */
    footnotes: FootnoteRules;

    /** Bibliography (final list) rules. */
    bibliography: BibliographyRules;

    /** Quotation conventions — block quotes, marks, ellipses. */
    quotations: QuotationRules;

    /** Greek/Hebrew transliteration if the guide specifies one. */
    transliteration: TransliterationRules | null;

    /**
     * Cómo se arma la portada (`CoverStyle`). Ausente en los manifiestos
     * anteriores al campo: se usa la de TMS (`coverStyleOf`).
     */
    cover?: CoverStyle | null;

    /**
     * Free-form rules the extractor couldn't structure. Rendered into
     * the prompt as a "miscellaneous additional rules" block so they
     * still influence the model even though the post-processor can't
     * enforce them. Each entry is a single localized sentence.
     */
    additionalRules: ReadonlyArray<string>;

    /**
     * Confidence + notes from the extraction run. The verification UI
     * surfaces these so the student knows where to double-check the
     * extracted rules before approving.
     */
    confidence: 'high' | 'medium' | 'low';
    extractionNotes: ReadonlyArray<string>;
}

/**
 * Footnote format for the two common cases (first occurrence of a
 * source vs. subsequent) plus ibid behavior.
 *
 * `template` is a string with named placeholders the post-processor
 * substitutes. Supported placeholders:
 *   - {author}       — full author name as listed in the source
 *   - {authorShort}  — surname only (or `citationKey` when set)
 *   - {title}        — full title
 *   - {titleShort}   — abbreviated title
 *   - {publisher}    — publisher name
 *   - {city}         — place of publication
 *   - {year}         — publication year
 *   - {pages}        — page or page range
 *   - {volume}       — volume number/letter
 *
 * Templates are descriptive, not generative — when the LLM emits a
 * citation, the post-processor parses it and re-formats per template.
 */
export interface FootnoteRules {
    /** Format used the FIRST time a source is cited. */
    firstMentionTemplate: string;
    /** Format used on every subsequent mention. */
    subsequentMentionTemplate: string;
    /** Concrete examples to show in the verification UI. */
    examples: ReadonlyArray<FootnoteExample>;
    /** Ibid behavior — when consecutive footnotes cite the same source. */
    ibid: IbidRules;
}

/** A worked example the verification UI renders so the student sees what citations will look like. */
export interface FootnoteExample {
    /** What the citation describes ("first cite of Lane WBC", "second cite of Lane WBC", "ibid"). */
    label: string;
    /** The rendered example string. */
    rendered: string;
}

export interface IbidRules {
    /** Whether the guide allows ibid at all. Some modern guides forbid it. */
    enabled: boolean;
    /**
     * What string replaces the source in an ibid footnote ("Ibid.",
     * "Idem", "Ibídem"). Ignored when `enabled` is false.
     */
    label: string;
    /**
     * Whether ibid + page number is allowed when the page differs
     * ("Ibid., 47") vs. requiring a fresh short form. Almost always
     * true; included for completeness.
     */
    allowPageOverride: boolean;
}

export interface BibliographyRules {
    /**
     * Format for a single bibliography entry. Same placeholders as
     * `FootnoteRules.firstMentionTemplate` but typically with author
     * surname-first, periods instead of commas, and no page numbers.
     */
    entryTemplate: string;
    /** Sort order of the bibliography list. */
    sortBy: 'author-surname' | 'order-of-appearance';
    /**
     * Whether multiple works by the same author use a 3-em dash
     * substitution ("———") for the repeated name. Turabian and SBL
     * both do this; some seminary guides don't.
     */
    useDashForRepeatedAuthors: boolean;
}

export interface QuotationRules {
    /**
     * Word count above which a quote should be set as a block (indented,
     * smaller font, no quote marks). Below the threshold, quotes are
     * inline with quote marks.
     */
    blockQuoteThresholdWords: number;
    /**
     * Primary (outer) quote mark — a literal Unicode character. Plain
     * string instead of an enum because the space of conventions is
     * open: straight `"`, curly `“…”`, French `«…»`, German `„…“`,
     * Spanish `«…»` plus secondary, etc. The post-processor reads the
     * raw character and substitutes verbatim.
     */
    primaryQuoteMark: string;
    /** Secondary (nested) quote mark. Same rationale as `primaryQuoteMark`. */
    secondaryQuoteMark: string;
    /** Ellipsis style ("...", ". . .", "…"). */
    ellipsis: string;
    /**
     * Brackets used around editorial interpolations. Stored as a
     * tuple-string ("[]", "()") so the post-processor can parse the
     * open/close pair when normalizing.
     */
    interpolationBrackets: '[]' | '()';
}

export interface TransliterationRules {
    /** Scheme name as the guide labels it ("SBL", "Latinized", "Library of Congress"). */
    scheme: string;
    /** Whether macrons / diacritics should be preserved. */
    useDiacritics: boolean;
    /**
     * Whether transliteration is REQUIRED for the body or only for
     * footnotes. Some seminaries want Greek script in body and
     * transliteration only for non-specialist readers.
     */
    bodyRequiresTransliteration: boolean;
}

/**
 * Sane TMS-style default applied when the user hasn't uploaded a
 * style guide. Keeps generation usable from the first run; the
 * student can upload a real guide later and re-extract.
 */
export const DEFAULT_TMS_STYLE_MANIFEST: StyleGuideManifest = {
    provenance: 'system-default',
    extractedAt: new Date(0),
    extractorModelId: '',
    citationStyleLabel: 'TMS / Turabian (default)',
    footnotes: {
        firstMentionTemplate: '{author}, {title} ({city}: {publisher}, {year}), {pages}.',
        subsequentMentionTemplate: '{authorShort}, {titleShort}, {pages}.',
        examples: [
            {
                label: 'Primera cita / first cite',
                rendered: 'William L. Lane, Hebrews 1–8, WBC 47A (Dallas: Word, 1991), 7.',
            },
            {
                label: 'Cita posterior / subsequent cite',
                rendered: 'Lane, Hebrews 1–8, 12.',
            },
            {
                label: 'Ibid',
                rendered: 'Ibid., 14.',
            },
        ],
        ibid: {
            enabled: true,
            label: 'Ibid.',
            allowPageOverride: true,
        },
    },
    bibliography: {
        entryTemplate: '{authorSurnameFirst}. {title}. {city}: {publisher}, {year}.',
        sortBy: 'author-surname',
        useDashForRepeatedAuthors: true,
    },
    quotations: {
        blockQuoteThresholdWords: 40,
        primaryQuoteMark: '"',
        secondaryQuoteMark: "'",
        ellipsis: '. . .',
        interpolationBrackets: '[]',
    },
    transliteration: {
        scheme: 'SBL',
        useDiacritics: true,
        bodyRequiresTransliteration: false,
    },
    additionalRules: [],
    confidence: 'high',
    extractionNotes: [],
};

export function buildDefaultStyleManifest(): StyleGuideManifest {
    return {
        ...DEFAULT_TMS_STYLE_MANIFEST,
        extractedAt: new Date(),
    };
}

// ── v1.7 — Editor validation ────────────────────────────────────────────

/**
 * One validation problem on a manifest patch. Validation is permissive
 * (warns instead of blocks) for fields the post-processor can tolerate
 * (e.g. an empty `additionalRules` entry); strict for fields that
 * would silently break generation (e.g. zero block-quote threshold,
 * empty quote marks, unknown placeholders in templates).
 */
export interface StyleManifestValidationIssue {
    /** Dot-path of the field, e.g. `"footnotes.firstMentionTemplate"`. */
    path: string;
    /** `'error'` blocks save; `'warning'` is informational. */
    severity: 'error' | 'warning';
    /**
     * Stable code so the UI can localize the message via i18n. The
     * helper does NOT return localized text — i18n lives in the web
     * layer.
     */
    code: ManifestValidationCode;
    /**
     * Optional context for messages that interpolate values
     * (e.g. unknown placeholder name).
     */
    context?: Record<string, string | number>;
}

export type ManifestValidationCode =
    | 'empty-template'
    | 'unknown-placeholder'
    | 'non-positive-threshold'
    | 'empty-quote-mark'
    | 'duplicate-additional-rule'
    | 'empty-additional-rule'
    | 'transliteration-empty-scheme'
    | 'cover-blank-lines-out-of-range';

/**
 * Placeholders recognized by `IStyleFormatter`. The editor warns the
 * user when a template references a placeholder we don't know how to
 * substitute — typo prevention, mostly.
 */
export const KNOWN_TEMPLATE_PLACEHOLDERS: ReadonlySet<string> = new Set([
    'author',
    'authorShort',
    'authorSurnameFirst',
    'title',
    'titleShort',
    'publisher',
    'city',
    'year',
    'pages',
    'volume',
]);

/**
 * Validates a manifest the user is about to save. Returns an array of
 * issues — empty array means OK to persist. The use case treats
 * `severity: 'error'` as fatal; the editor surfaces warnings inline
 * but lets the user save through them.
 *
 * Pure function. No mutation, no side effects.
 */
export function validateStyleGuideManifest(manifest: StyleGuideManifest): ReadonlyArray<StyleManifestValidationIssue> {
    const issues: StyleManifestValidationIssue[] = [];

    // ── Footnotes ──────────────────────────────────────────────────────
    if (!manifest.footnotes.firstMentionTemplate.trim()) {
        issues.push({ path: 'footnotes.firstMentionTemplate', severity: 'error', code: 'empty-template' });
    } else {
        for (const placeholder of extractPlaceholders(manifest.footnotes.firstMentionTemplate)) {
            if (!KNOWN_TEMPLATE_PLACEHOLDERS.has(placeholder)) {
                issues.push({
                    path: 'footnotes.firstMentionTemplate',
                    severity: 'warning',
                    code: 'unknown-placeholder',
                    context: { placeholder },
                });
            }
        }
    }
    if (!manifest.footnotes.subsequentMentionTemplate.trim()) {
        issues.push({ path: 'footnotes.subsequentMentionTemplate', severity: 'error', code: 'empty-template' });
    } else {
        for (const placeholder of extractPlaceholders(manifest.footnotes.subsequentMentionTemplate)) {
            if (!KNOWN_TEMPLATE_PLACEHOLDERS.has(placeholder)) {
                issues.push({
                    path: 'footnotes.subsequentMentionTemplate',
                    severity: 'warning',
                    code: 'unknown-placeholder',
                    context: { placeholder },
                });
            }
        }
    }

    // ── Bibliography ───────────────────────────────────────────────────
    if (!manifest.bibliography.entryTemplate.trim()) {
        issues.push({ path: 'bibliography.entryTemplate', severity: 'error', code: 'empty-template' });
    } else {
        for (const placeholder of extractPlaceholders(manifest.bibliography.entryTemplate)) {
            if (!KNOWN_TEMPLATE_PLACEHOLDERS.has(placeholder)) {
                issues.push({
                    path: 'bibliography.entryTemplate',
                    severity: 'warning',
                    code: 'unknown-placeholder',
                    context: { placeholder },
                });
            }
        }
    }

    // ── Quotations ─────────────────────────────────────────────────────
    if (manifest.quotations.blockQuoteThresholdWords <= 0) {
        issues.push({
            path: 'quotations.blockQuoteThresholdWords',
            severity: 'error',
            code: 'non-positive-threshold',
        });
    }
    if (!manifest.quotations.primaryQuoteMark.trim()) {
        issues.push({ path: 'quotations.primaryQuoteMark', severity: 'error', code: 'empty-quote-mark' });
    }
    if (!manifest.quotations.secondaryQuoteMark.trim()) {
        issues.push({ path: 'quotations.secondaryQuoteMark', severity: 'error', code: 'empty-quote-mark' });
    }

    // ── Transliteration ────────────────────────────────────────────────
    if (manifest.transliteration && !manifest.transliteration.scheme.trim()) {
        issues.push({
            path: 'transliteration.scheme',
            severity: 'error',
            code: 'transliteration-empty-scheme',
        });
    }

    // ── Additional rules ───────────────────────────────────────────────
    const seenRules = new Set<string>();
    manifest.additionalRules.forEach((rule, idx) => {
        const trimmed = rule.trim();
        if (trimmed.length === 0) {
            issues.push({
                path: `additionalRules.${idx}`,
                severity: 'warning',
                code: 'empty-additional-rule',
            });
            return;
        }
        const normalized = trimmed.toLowerCase();
        if (seenRules.has(normalized)) {
            issues.push({
                path: `additionalRules.${idx}`,
                severity: 'warning',
                code: 'duplicate-additional-rule',
            });
        } else {
            seenRules.add(normalized);
        }
    });

    // ── Portada ────────────────────────────────────────────────────────
    if (manifest.cover) {
        const { layout } = manifest.cover;
        for (const [campo, n] of Object.entries(layout)) {
            if (!Number.isInteger(n) || n < 0 || n > 20) {
                issues.push({ path: `cover.layout.${campo}`, severity: 'error', code: 'cover-blank-lines-out-of-range' });
            }
        }
    }

    return issues;
}

/**
 * True when `validateStyleGuideManifest` returned at least one
 * `severity: 'error'` issue. Convenience for the use case's gate.
 */
export function hasManifestValidationErrors(
    issues: ReadonlyArray<StyleManifestValidationIssue>,
): boolean {
    return issues.some(i => i.severity === 'error');
}

/**
 * Pulls `{placeholder}` substrings out of a template string. Used
 * internally by `validateStyleGuideManifest` and exposed so the
 * editor can render highlighted placeholder badges.
 */
export function extractPlaceholders(template: string): ReadonlyArray<string> {
    const matches = template.matchAll(/\{([a-zA-Z][a-zA-Z0-9]*)\}/g);
    const out: string[] = [];
    for (const m of matches) {
        if (m[1]) out.push(m[1]);
    }
    return out;
}
