/**
 * Core domain entities for verse analysis.
 *
 * VerseAnalysis is the aggregate root for the productive analysis tool.
 * It contains all data generated by the Gemini service applying
 * Farfán's rules and the professor's lessons to a Hebrew verse.
 */

import {
  Binyan,
  GrammaticalCategory,
  GrammaticalNumber,
  Gender,
  MorphemeRole,
  NominalState,
  Person,
  VerbForm,
  VerbType,
} from '../value-objects/grammar.js';

// ── Morpheme Segment ──────────────────────────────────────────────────────────

/**
 * A single morpheme within a Hebrew word, annotated for visual rendering.
 * Maps directly to the dual-layer color system (morphological + phonetic).
 */
export interface MorphemeSegment {
  readonly text: string;
  readonly role: MorphemeRole;
  /** Short label for tooltip/accessibility, e.g. "preformativo Hitpael" */
  readonly label: string;
}

// ── Word Analysis ─────────────────────────────────────────────────────────────

/** Morphological analysis specific to verbs. */
export interface VerbMorphology {
  readonly binyan: Binyan;
  readonly verbForm: VerbForm;
  readonly verbType: VerbType;
  /**
   * Lexical root classification — the actual identity of the root.
   * Separates root identity from morphological behavior.
   * Example: הלך → rootClassification = "Pe-He (פ״ה)"
   *          verbType = I_YOD_WAW (because it behaves like Pe-Yod)
   * When absent, verbType is used for both display and routing.
   */
  readonly rootClassification?: string;
  readonly person?: Person;
  readonly gender?: Gender;
  readonly number?: GrammaticalNumber;
  /** Temporal / aspectual value, e.g. "pasado narrativo secuencial" */
  readonly temporalValue: string;
  /** Recognition clues derived from Farfán's rules, e.g. ["דוּ duplica R2 → Piel"] */
  readonly recognitionClues: readonly string[];
}

/** Morphological analysis specific to nouns, adjectives, and pronouns. */
export interface NominalMorphology {
  readonly gender?: Gender;
  readonly number?: GrammaticalNumber;
  readonly state?: NominalState;
  readonly person?: Person;
  readonly suffix?: {
    readonly person: Person;
    readonly gender: Gender;
    readonly number: GrammaticalNumber;
  };
}

/**
 * Complete analysis of a single Hebrew word within a verse.
 * Morphological data comes from Gemini applying Farfán's grammar rules.
 */
export interface WordAnalysis {
  /** Fully vocalized Hebrew text of this word as it appears in the verse */
  readonly hebrewText: string;
  /** Academic transliteration */
  readonly transliteration: string;
  /** Trilateral (or other) root form */
  readonly root: string;
  /** Academic transliteration of the root, e.g. "m-n-h" for מנה */
  readonly rootTransliteration?: string;
  /** Meaning of the root, e.g. "arrojar, lanzar" */
  readonly rootMeaning: string;
  /** Lexical/dictionary gloss */
  readonly lemmaGloss: string;
  /** Part of speech */
  readonly category: GrammaticalCategory;
  /** Syntactic role in the clause, e.g. "verbo principal de la oración" */
  readonly syntacticFunction: string;
  /** Contextual translation of this specific word/phrase */
  readonly translation: string;
  /** Detailed pedagogical explanation following professor's methodology */
  readonly explanation: string;

  /** Present only for verbs */
  readonly verbMorphology?: VerbMorphology;
  /** Present for nouns, adjectives, pronouns */
  readonly nominalMorphology?: NominalMorphology;

  /** Visual segments with morpheme roles for color rendering */
  readonly morphemes: readonly MorphemeSegment[];

  /**
   * Explicit syntactic clause tag used for visual overlay markers.
   * Derived by Gemini for new analyses; absent in legacy cached analyses
   * (the UI falls back to category/nominalMorphology.state/syntacticFunction).
   */
  readonly clauseTag?: 'PREP_PHRASE' | 'CONSTRUCT' | 'APPOSITION' | null;

  /**
   * Optional cross-reference data from OSHB (morphhb database).
   * Visible in the UI so the user can evaluate discrepancies.
   */
  readonly oshbReference?: OshbReference;
}

/** Un rasgo del verbo que OSHB corrigió: lo que decía el análisis y lo que dice OSHB. */
export interface OshbCorrection {
  readonly field: 'binyan' | 'verbForm' | 'person' | 'gender' | 'number';
  readonly analysis: string;
  readonly oshb: string;
}

/**
 * La palabra según OSHB (morphhb), que DECIDE la morfología del verbo.
 *
 * Antes era sólo informativa y el asistente la contradecía en las formas
 * ambiguas (2FP/3FP, yusivo/imperfecto). Ver `services/oshb-contrast.ts`.
 */
export interface OshbReference {
  /** Código de morphhb, p. ej. "HVqw3ms". */
  readonly morphCode: string;
  /** Lema de morphhb (número de Strong con prefijo), p. ej. "c/1961". */
  readonly strongNumber: string;
  /** El análisis coincidía con OSHB. */
  readonly agreesWithAnalysis: boolean;
  /** Lo que se corrigió con OSHB. Vacío si coincidía. */
  readonly corrections: readonly OshbCorrection[];
}

// ── Verb Table ────────────────────────────────────────────────────────────────

/** Summary row for the verb table shown at the bottom of a verse analysis. */
export interface VerbTableEntry {
  readonly hebrewForm: string;
  readonly transliteration: string;
  readonly root: string;
  readonly rootTranslation: string;
  readonly binyan: Binyan;
  readonly verbForm: VerbForm;
  readonly verbType: VerbType;
  /** Lexical root classification, e.g. "Pe-He (פ״ה)" when it differs from verbType behavior. */
  readonly rootClassification?: string;
  readonly temporalValue: string;
  /** Person, gender, number abbreviated label, e.g. "3ms" */
  readonly pgn: string;
}

// ── Lexical Notes ─────────────────────────────────────────────────────────────

/** Classifies the type of lexicographic observation. */
export type LexicalNoteType = 'idiom' | 'semantic_range' | 'cultural_note' | 'false_friend';

/**
 * A single lexicographic observation generated by the LLM for a phrase or word
 * in the verse. Surfaces the gap between literal and idiomatic meaning.
 *
 * Both translations coexist: the literal form is preserved unchanged in
 * `VerseAnalysis.literalTranslation`; the idiomatic form is used in
 * `VerseAnalysis.fluidTranslation` and documented here for pedagogical clarity.
 */
export interface LexicalNote {
  /** The Hebrew phrase or word this note applies to, e.g. "חַיַּת הַשָּׂדֶה" */
  readonly hebrewPhrase: string;
  /** Word-for-word meaning of the phrase, e.g. "criatura viviente del campo" */
  readonly literalMeaning: string;
  /** Dynamic-equivalent meaning used in fluent translation, e.g. "animales salvajes" */
  readonly idiomaticMeaning: string;
  /** Academic explanation of the semantic gap, suitable for seminary level */
  readonly explanation: string;
  /** Category of lexicographic observation */
  readonly type: LexicalNoteType;
}

// ── Clauses ───────────────────────────────────────────────────────────────────

/**
 * Cómo se une una cláusula a lo anterior.
 *
 *   FIRST             — primera del versículo y sin conector que analizar.
 *   WAYYIQTOL_CHAIN   — וַ + prefijo: sigue la cadena narrativa.
 *   WAW_CONJUNCTIVE   — וְ + verbo: coordinación simple (incluye weqatal).
 *   WAW_DISJUNCTIVE   — וְ + NO verbo (sujeto, objeto, adverbio adelante):
 *                       rompe la cadena; contraste, circunstancia, paréntesis.
 *                       Rut 1:14 «וְרוּת דָּבְקָה בָּהּ» = «pero Rut se quedó».
 *   ASYNDETIC         — empieza SIN conjunción: asíndeton.
 *                       Rut 1:16 «עַמֵּךְ עַמִּי».
 *   SUBORDINATE       — introducida por כִּי, אֲשֶׁר, אִם, לְמַעַן, כַּאֲשֶׁר…
 *   QUOTATION         — comienzo de discurso directo.
 */
export type ClauseConnection =
  | 'FIRST' | 'WAYYIQTOL_CHAIN' | 'WAW_CONJUNCTIVE' | 'WAW_DISJUNCTIVE'
  | 'ASYNDETIC' | 'SUBORDINATE' | 'QUOTATION';

/** Una cláusula del versículo: qué palabras abarca, de qué tipo es y cómo se une. */
export interface VerseClause {
  /** Índice (desde 0) de la primera palabra en `words`. */
  readonly firstWord: number;
  /** Índice de la última palabra, inclusive. */
  readonly lastWord: number;
  readonly type: 'VERBAL' | 'NOMINAL';
  readonly connection: ClauseConnection;
  /** El conector en hebreo (וְ, כִּי, אֲשֶׁר…), o `null`. */
  readonly connector: string | null;
  /** Valor lógico en palabras: «contraste», «circunstancia», «causa», «clímax»… */
  readonly value: string;
  /** Una frase que lo explica al estudiante. */
  readonly explanation: string;
  /** La conexión que dio el asistente se corrigió con la regla de la waw. */
  readonly adjusted?: boolean;
}

// ── Verse Analysis ────────────────────────────────────────────────────────────

/**
 * Aggregate root: the complete morphological and syntactic analysis
 * of a single Hebrew Bible verse.
 */
export interface VerseAnalysis {
  /** Human-readable reference, e.g. "Jonás 2:3" */
  readonly reference: string;
  /** Full vocalized Hebrew text of the verse */
  readonly hebrewText: string;
  /** Academic transliteration of the full verse */
  readonly transliteration: string;
  /** Word-for-word (literal) translation */
  readonly literalTranslation: string;
  /** Fluent translation capturing the sense */
  readonly fluidTranslation: string;
  /** Ordered word-by-word analyses */
  readonly words: readonly WordAnalysis[];
  /** Summary table of verbal forms in the verse */
  readonly verbTable: readonly VerbTableEntry[];
  /** Las cláusulas del versículo. Ausente en análisis guardados antes de existir. */
  readonly clauses?: readonly VerseClause[];
  /** Optional exegetical or syntactic observations */
  readonly exegeticalNotes?: readonly string[];
  /**
   * Lexicographic observations: idioms, semantic ranges, cultural notes,
   * and false friends detected in this verse.
   * These complement (never replace) the `literalTranslation`.
   */
  readonly lexicalNotes?: readonly LexicalNote[];
  /** ISO timestamp of when this analysis was generated */
  readonly analyzedAt: string;
}
